### ISSUE TITLE
MauiLocalization not work under MacCatalyst when compile at release mode for arm64

### ISSUE THREAD

**Issue by changguangyu** [VladislavAntonyuk/MauiSamples#151] opened 2022-11-18 13:14 UTC
I compiled the demo with Visual Studio 17.4 and .Net 7.0. (Tested on both Win and Mac )
Switch language not work under iOS.
But on windows and Android it's working fine.

**Comment by VladislavAntonyuk** [comment] 2022-11-19 17:29
https://user-images.githubusercontent.com/33021114/202863821-773c7329-757b-4494-b0b2-697162ac0e3e.mov

**Comment by VladislavAntonyuk** [comment] 2022-11-19 18:44
The issue is reproduced on MacCatalyst, but the issue itself is in ResourceManager, that incorrectly reads resource objects

**Comment by changguangyu** [comment] 2022-11-20 03:16
> The issue is reproduced on MacCatalyst, but the issue itself is in ResourceManager, that incorrectly reads resource objects

Thanks for the reply. It seems that satellite assemblies are not properly packaged on MacCatalyst when compile at release mode for arm64. I've reported the issue to MAUI team here: [https://github.com/dotnet/maui/issues/11474](url)

**Comment by VladislavAntonyuk** [comment] 2022-11-20 07:34
@changguangyu You mentioned it doesn't work on iOS. Is it only in release?

**Comment by changguangyu** [comment] 2022-11-20 13:08
> @changguangyu You mentioned it doesn't work on iOS. Is it only in release?

I tested it on iOS again with Visual Studio for Mac 17.4, both debug and release mode, stimulator and read device, there is no issue now. That's weird.

**Comment by changguangyu** [comment] 2022-11-21 00:52
> @changguangyu You mentioned it doesn't work on iOS. Is it only in release?

After I submit my app to App Store, it doesn't work on iOS again. But it works fine in both release and debug mode. It seems that the "optimization" process when generate distribution package broked the app.

**Comment by VladislavAntonyuk** [comment] 2023-01-21 06:26
Fixed by https://github.com/xamarin/xamarin-macios/issues/16847

**Closed by VladislavAntonyuk** 2023-01-21 06:26 UTC
