### ISSUE TITLE
IDialog wont work under Android

### ISSUE THREAD

**Issue by DeepWorksStudios** [VladislavAntonyuk/MauiSamples#24] opened 2022-06-20 10:55 UTC
it does not work (Save&Read) aswell it cant create a new folder or display right paths

**Comment by VladislavAntonyuk** [comment] 2022-06-20 11:07
could you please provide more details?

**Comment by DeepWorksStudios** [comment] 2022-06-20 11:16
On the Exsample Project MauiPaint
if you run it on Android you cant save or open the file 

it does not trow any msg or similar. Its the stock project 
you can simply test it and see the result
as well you cant create a folder and the paths does not exists

all under android 
windows seems fine 

if you need any more information let me know i am highly intrested to solve that beacuse i dependt on a file picker

**Comment by VladislavAntonyuk** [comment] 2022-06-20 12:25
Have you enabled the storage permission?

**Comment by DeepWorksStudios** [comment] 2022-06-20 12:37
Of course

**Comment by DeepWorksStudios** [comment] 2022-06-20 13:36
i checked promission on manifest
![image](https://user-images.githubusercontent.com/59297046/174613034-23028bf1-3ae1-4b9a-aaca-07a690022aa5.png)
i checked promission on the phone aswell
![image](https://user-images.githubusercontent.com/59297046/174613161-50bd631e-3b21-4b84-aa82-108d6e019478.png)
Those paths doesn't exist even
![image](https://user-images.githubusercontent.com/59297046/174613062-b997fe79-0970-4a16-be95-7e4eea94061d.png)
See there the prove
![image](https://user-images.githubusercontent.com/59297046/174613361-6e9af01e-4cf3-4fc9-abe5-feec4040d6af.png)

**Comment by VladislavAntonyuk** [comment] 2022-06-20 13:53
it's the path to root. You can change it to your own path.
https://github.com/VladislavAntonyuk/MauiSamples/blob/main/MauiPaint/Platforms/Android/Services/FileDialog.cs#L74

**Comment by VladislavAntonyuk** [comment] 2022-06-20 18:46
I will check tomorrow, but I suggest you to check what path you pass to the method.

**Comment by VladislavAntonyuk** [comment] 2022-06-21 12:07
@DeepWorksStudios I can't reproduce it:
On click Save:
![image](https://user-images.githubusercontent.com/33021114/174791529-a4f97439-1daf-42b6-b785-7620977412c2.png)

On click Open:
![image](https://user-images.githubusercontent.com/33021114/174791620-e9f7a2fb-655f-4226-873d-8e6ef6d1002d.png)

**Comment by DeepWorksStudios** [comment] 2022-06-21 12:39
I will create a repo for redproducing the bug but it will take some time 
approxi next day Thanks for the support

**Comment by VladislavAntonyuk** [comment] 2022-06-21 15:48
from what I see, you shared the screen from SDCard, the folders you see are the internal storage.

To see the folders you can open emulated/0/

**Comment by VladislavAntonyuk** [comment] 2022-06-23 12:08
I've just merged the branch which should fix your issue. please try again

**Comment by DeepWorksStudios** [comment] 2022-06-24 16:41
I extendly tested the mauipaint under diffrent viraritys of andrid version and all under api level 30 wont work thats why it does not work on my project. Just pull the maui paint project add android emulator api level 23 thats the minimun for the project to run and see the results. My personal device was api level 29 there the pictures come from but i observed every version had the same problems 

cant save cant load and wrong paths

**Comment by DeepWorksStudios** [comment] 2022-06-27 06:58
If i may ask, could you reproduce it?

**Comment by VladislavAntonyuk** [comment] 2022-06-27 09:37
I've just tried it on Android 6.0.1. And see all my files:
![Screenshot_2022-06-27-12-27-41](https://user-images.githubusercontent.com/33021114/175909054-f6589309-c147-4c1d-a201-af7312ffe0e6.png)
![Screenshot_2022-06-27-12-31-47 (1)](https://user-images.githubusercontent.com/33021114/175909254-61b17272-0823-45d2-b602-e41fbb89117f.png)

**Comment by VladislavAntonyuk** [comment] 2022-06-27 19:41
Could you please pull the latest changes? It contains fix for the Paint app

**Comment by DeepWorksStudios** [comment] 2022-06-28 09:35
I pulled your latest commit and it did not change the case sadly 

The path exist not :/ i enabled invisable folders checked local storage external storage read/wirte promission

i really dont know what to do 

https://user-images.githubusercontent.com/59297046/176146001-167351d0-de07-4e0f-a299-da831140eebf.mp4

**Comment by VladislavAntonyuk** [comment] 2022-06-28 10:48
I had the same issue when I didn't get permission to the storage for the app. Open App settings and make sure you allowed the access to the storage

**Comment by DeepWorksStudios** [comment] 2022-06-28 10:58
I did that already. Same result 
![Screenshot_20220628-125717_Permission controller.jpg](https://user-images.githubusercontent.com/59297046/176162795-3627c7f9-2f0f-4adc-8f9f-dc8c0a9955f9.jpg)

**Comment by DeepWorksStudios** [comment] 2022-06-28 16:53
Its unmodified newest commit from you

https://user-images.githubusercontent.com/59297046/176236561-708f67d2-ff2a-4c36-9ee5-432c0c3d8f74.mp4

**Comment by VladislavAntonyuk** [comment] 2022-06-28 19:00
Sorry, I don't know. By default the phone storage is "storage/emulated/0". You can try to traverse the file system to get the path you need.

**Comment by VladislavAntonyuk** [comment] 2022-06-30 11:24
I added a check to make sure storage permission is granted.
You can try to add `android:requestLegacyExternalStorage="true"` in your AndroidManifest.xml

**Comment by DeepWorksStudios** [comment] 2022-07-01 05:59
I will try that thanks :)

**Comment by Cairn23** [comment] 2022-08-25 08:47
I like the idea of the Dialogue service, but when I attempted to reuse your code to do this I keep getting a build error with MauiProgram.cs "CS0246 The type or namespace name 'DialogService' could not be found (are you missing a using directive or an assembly reference?)". Other than just using the code, is there a config setting to allow the serice to be seen and allow the build

**Comment by VladislavAntonyuk** [comment] 2022-08-25 14:21
Make sure you added it for all platforms

**Comment by Cairn23** [comment] 2022-08-26 08:26
It has been added to all platforms with the exception of Tizen, but I did not see this in your sample either. Is there a project setting that needs to be set so that the device type (Windows, Tizen etc) gets stripped out?

**Comment by VladislavAntonyuk** [comment] 2022-08-26 10:19
If you attach a small repro, I can help you

**Comment by Cairn23** [comment] 2022-08-28 15:20
First of all thank you very much for the offer of help.

 

 

I have removed a lot of the other code in order to just get to the problem.

 

Within MauiProgram.cs when ever I enable

builder.Services.AddSingleton<IDialogService, DialogService>();

the App will not build.

 

I have also has to mess with the FileDialog.cs withint he Android Platform services, but I think that is more a case of the incorrect set of usings.

 

Please find attached a zip of the code.

**Comment by VladislavAntonyuk** [comment] 2022-08-28 17:55
@Cairn23 Please attach the sample using GitHub. It is not attached when you send it using email

**Comment by Cairn23** [comment] 2022-08-29 15:47
I have attached the files
[ShipDesigner - Dialog Bug.zip](https://github.com/VladislavAntonyuk/MauiSamples/files/9445998/ShipDesigner.-.Dialog.Bug.zip)

**Comment by VladislavAntonyuk** [comment] 2022-08-29 19:02
Pay attention on namespace. All dialog service should have the same namespace or you need to import the namespace in MauiProgram.

**Comment by VladislavAntonyuk** [comment] 2022-09-04 18:40
@Cairn23 have you solved the issue?

**Comment by VladislavAntonyuk** [comment] 2022-09-04 18:43
in your specific case add the next code in your MauiProgram:
```
#if __ANDROID__
using ShipDesigner.Platforms.Android.Services;
#elif MACCATALYST
using ShipDesigner.Platforms.MacCatalyst.Services;
#elif __IOS__
using ShipDesigner.Platforms.iOS.Services;
#elif WINDOWS
using ShipDesigner.Windows.Services;
#endif
```

**Comment by Cairn23** [comment] 2022-09-05 07:35
Yes thanks. After seeing your note, and chnaged the namespaces for all the types of devices to be the same, and resolved it that way.

**Closed** 2022-09-05 07:53 UTC
