### ISSUE TITLE
OnMapReady in MapCallbackHandler clears all objects added to the map

### ISSUE THREAD

**Issue by anotherlab** [VladislavAntonyuk/MauiSamples#125] opened 2022-10-21 20:36 UTC
The call to [googleMap.Clear()](https://github.com/VladislavAntonyuk/MauiSamples/blob/ef34254916ceee8f4c8bdc581e6eeca52388ec13/MauiMaps/Platforms/Android/MapCallbackHandler.cs#L17) in OnMapReady has a side affect of clearing anything else added to the map.  If you added any shapes or polylines, they will get removed after Clear() is called.

**Comment by VladislavAntonyuk** [comment] 2022-10-24 14:43
I am working on the fix for this issue.
The problem is that we do not have access to the Markers collection.

The workaround is create a custom map with custom bindable property Markers. It will store all MAUI pins and custom pins. MAUI pins will be always empty to make sure we do not display the same marker twice.

The best solution if .NET MAUI team provides the access to stored polygons, markers etc

**Comment by anotherlab** [comment] 2022-10-24 14:57
Can you override CreateMarker() and assign the bitmap there?  You don't need access to the Markers collection if you get access to each marker as it's being created from a pin (or pin descendent).

**Comment by VladislavAntonyuk** [comment] 2022-10-25 13:38
Marker is created from MarkerOptions. AddMarker is not virtual. Even if I update MarkerOptions (it is a native realization of MAUI MapPin), marker is not updated.

**Closed** 2022-10-25 14:41 UTC
